[project]
name = "bookroom-agents"
version = "0.0.1"
description = "About API for Agents."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "argparse>=1.4.0",
    "ascii-colors>=0.5.2",
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.0",
]
authors = [
    { name = "sndraw" },
]
[project.urls]
"Homepage" = "https://github.com/sndraw/bookroom-agents"
"Documentation" = "http://localhost:15230/docs"

[tool.setuptools.packages.find]
where = ["./"]
include = ["app"]
exclude = []
